### ISSUE TITLE
Is it possible to build for raspberry pi?

### ISSUE THREAD

**Issue by olehbozhok** [shouya/rss-funnel#109]
I have a pretty old raspberry pi with the target `arm-unknown-linux-gnueabihf` 
Could you guide me how to build it for pi?
Or why it is impossible for now and what we need to replace/improve to make building possible.

**Comment by olehbozhok** [comment]
looks line the root of problem if https://github.com/DelSkayn/rquickjs that not support target

**Comment by shouya** [comment]
Although `arm-unknown-linux-gnueabi-hf` is not a supported target by rquickjs, I was able to get rquickjs successfully built with its bindgen feature. The rest of rss-funnel compiles with no problems.

However, I don't have the hardware to test the build. Can you please help try out the branch at https://github.com/shouya/rss-funnel/pull/110? If the it works fine for you, let me know and I will add the target to CI and build Docker image for it.

**Comment by olehbozhok** [comment]
I made litle changes. So now it works.
Pls look at
https://github.com/shouya/rss-funnel/pull/111 
Thanks for guiding me
