### ISSUE TITLE
Ensure `simplify_html` Provides Complete Output

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#121]
I believe the `simplify_html` function requires the `full_text` method to work effectively. Mentioning only `simplify_html` on the URL parameter can cause confusion for end users, as it does not provide the expected output on its own.

If it's not possible to modify the function, we can update the wiki to highlight that for [readability](https://github.com/kumabook/readability) purposes, both `simplify_html` and `full_text` need to be used together.

**Comment by shouya** [comment]
The `simplify_html` filter takes in a feed whose entries may contain excessive html tags in the body and strip those tags away. I'm supposing it's mostly useful if the body was fetched using `full_text` filter, but `simplify_html` and `full_text`, in my humble opinion, refer to two independent way to processing the feed.

Sorry I may have misunderstood your question here. I'm a bit confused what you mean by "Mentioning only simplify_html on the URL parameter"? Could you elaborate a bit?

Oh, by the way, the wiki should be open for everyone to edit. Please feel free to edit the wiki directly if you see fit.

**Comment by shouya** [comment]
Thank you for your clarification. I have made [some changes](https://github.com/shouya/rss-funnel/wiki/Filter-config/_compare/98d8ef2b2d5eb1670ad9bfdcc7f9e4943468b6cf...914c39d7057c3c5e050d26c6140534566d9f0907) on top of your update.

Note that different feed formats have different fields for the content. For Atom the content is sometimes found in the `<content>` or `<summary>` tag, and for RSS the body is more often found in `<description>`. It is a [quite messy thing](https://github.com/shouya/rss-funnel/blob/master/src/feed.rs#L438-L472) to deal with. From the code and some docs, I used the generic term "body" to avoid confusion.
