### ISSUE TITLE
Feature Request: Local Caching with No Image Expiry for Image Proxy

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#127]
I would like to request a feature that enables local caching with no image expiry for the image proxy. This feature would be particularly useful for feeds where images are frequently removed after a short period, such as Telegram and 4chan. Implementing this would ensure that images remain accessible even after they have been deleted from the original source.

Please feel free to close this issue if it is not feasible.

**Comment by shouya** [comment]
I see the need and usefulness for this type of image caching. But sorry I'm not planning to support local caching. The original purpose of the `image_proxy` filter is to fix image issues for sites fetched with `full_text` filter. rss-funnel is (current) designed as a stateless system to reduce complexity; also I expect the app to run with (mostly) constant memory usage and produce no external files. 

For the purpose of image caching, I suggest you look for other image proxy software/service. For example the service provided by https://images.weserv.nl/ is an excellent one. The `image_proxy` filter already supports rewriting image tag sources with external image proxy.
