### ISSUE TITLE
Feature Request: Add Support for Health Check in Docker Image

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#128]
Health checks are crucial for ensuring the application is running correctly and can help with creating dependencies on and automated recovery and maintenance processes.

[Docker Healthcheck Documentation](https://docs.docker.com/reference/dockerfile/#healthcheck)

**Comment by shouya** [comment]
There is an healthcheck endpoint at `http://127.0.0.1:4080/health`.

To use the docker `HEALTHCHECK` command the image must contains a http client like `curl` to query that. Currently the docker image is built from scratch in an one-liner: https://github.com/shouya/rss-funnel/blob/master/Makefile#L47, such that the image contains only a single executable an nothing else, not even the rootfs for some Linux. To install `curl` or copy the binary from external place would require breaking that, which is against my intention.

However, it should be easy to add a healthcheck subcommand to the rss-funnel binary itself, that would eliminate the need for `curl` or other tools. I will try to implement it in the future.
