### ISSUE TITLE
URL issues in inspector UI

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#131]
If I use `https://rssbridge.flossboxin.org.in/?action=display&bridge=TelegramBridge&username=aboutrss&format=Atom`, it generates the attached error. However, if I encode it as `https%3A%2F%2Frssbridge.flossboxin.org.in%2F%3Faction%3Ddisplay%26bridge%3DTelegramBridge%26username%3Daboutrss%26format%3DAtom`, it works fine.

![image](https://github.com/user-attachments/assets/ee9096b8-6c8b-4b26-a55c-ec02957d429f)

The issue arises when clicking the `Copy URL` button, which generates the URL `/image-proxy1.xml?source=https%253A%252F%252Frssbridge.flossboxin.org.in%252F%253Faction%253Ddisplay%2526bridge%253DTelegramBridge%2526username%253Daboutrss%2526format%253DAtom`, resulting in a `missing source` error when i try to access the link.

**Comment by shouya** [comment]
Fixed. Thanks for reporting <3
