### ISSUE TITLE
Problem to build project because of dependency atom_syndication

### ISSUE THREAD

**Issue by olehbozhok** [shouya/rss-funnel#140]
Thanks for this great project.

I decided to update my server and found that I can`t.
I have the problem atom_syndication of building package atom_syndication.

Also I have tried on last master commit.
to reproduce you can run 
```
cross build --release --target x86_64-unknown-linux-musl
```
or 
```
cross build -r --target arm-unknown-linux-gnueabihf
```
this one is for my raspberry pi

**Comment by shouya** [comment]
Do you use x86_64 as your host? If so you do not need cross to build for `x86_64-unknown-linux-musl`. You can just build with cargo: `cargo build --release --target x86_64-unknown-linux-musl`.

For building `arm-unknown-linux-gnueabihf` you can refer to the CI environment and build steps for nightly build, which runs for commits on the master branch. Here: https://github.com/shouya/rss-funnel/actions/workflows/nightly.yaml. Let me know if you still need my help.

**Comment by shouya** [comment]
I realized the CI doesn't build for arm-unknown-linux-gnueabihf by default although the build instructions are in the Makefile. I tried building for the target locally and succeeded without error. Please try the following command.

```
make target/arm-unknown-linux-gnueabihf/release/rss-funnel
```

**Comment by olehbozhok** [comment]
After removing a cache of crates, it had been compiled.
```
cargo cache --autoclean
```
... interesting. Thanks for your time.

**Comment by olehbozhok** [comment]
but found new problem... new not compatible version of glibc... but it is not your fault
