### ISSUE TITLE
Endpoints Showing Invalid Domain Name After Recent Commits

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#161]
After recent commits, all the endpoints are showing ` _` instead of the domain name, for example, `https://_/endpoint/youtube-cnet.xml`, with no valid domain name. I am using Caddy as a reverse proxy with the following configuration:

```
*.{$DOMAIN} {
    tls {
        dns cloudflare {$CF_API_TOKEN}
        resolvers 1.1.1.1
    }

    @rssfunnel host rssfunnel.{$DOMAIN} rf.{$DOMAIN}
    handle @rssfunnel {
        reverse_proxy rssfunnel:4080
    }

    handle {
        abort
    }
}
```

I didn't change any configuration; it was working fine before. The documentation states that I don't need to change anything manually if I'm using Caddy.

**Comment by shouya** [comment]
Thanks for reporting. This bug is almost certainly caused by the changes in https://github.com/shouya/rss-funnel/pull/160. I will figure out what went wrong. For the time being please rollback to the previous nightly release.
