### ISSUE TITLE
Docker image not accessible

### ISSUE THREAD

**Issue by dulli** [shouya/rss-funnel#3]
Hi, while wanting to try rss-funnel I saw that the docker image you mention in your docker-compose example (`ghcr.io/shouya/rss-funnel:0.0.1`) is not available.

I think Github registries are set to private by default, so this may be the problem? Or should I just build it with my own Dockerfile?

**Comment by shouya** [comment]
Oh thanks for reminding me on that. I forgot to change the visibility after pushing the image. Please try it again and let me know if it works.

**Comment by dulli** [comment]
Yes, now it works. I played around a bit with the command and added a `-b 0.0.0.0:80`, so that I can fetch the endpoints from a miniflux instance in the same stack / docker network. Thanks for the quick response!
