### ISSUE TITLE
ARM compatibility

### ISSUE THREAD

**Issue by uGeek** [shouya/rss-funnel#4]
Could you add arm64 compatibility?

Thanks

```
 ! rss-funnel The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by shouya** [comment]
I just added linux/arm64/v8 platform in 59ea7fd488a9891f5d0e7d9fc4620eff6bd8e6df. So you should be able to just use `ghcr.io/shouya/rss-funnel:0.0.3` image tag. Can you please help try out if the multiarch docker image works?

If it still fails, try `ghcr.io/shouya/rss-funnel:0.0.3-aarch64-unknown-linux-musl`. Please let me know which one works.

Sorry it's the first time I build a multiarch docker image, and I don't get an amd64 node to test it, so it may not work right away. I will follow up if you provide enough information to resolve any issues.

**Comment by shouya** [comment]
You need to bind to `0.0.0.0` - change the command line in the `docker-compose.yaml` from

```yaml
    command: /rss-funnel -c /funnel.yaml server
```

to

```yaml
    command: /rss-funnel -c /funnel.yaml server -b 0.0.0.0
```

I will update the readme (and probably the default bind address) later.

**Comment by uGeek** [comment]
With this command I get this error:

```
rss-funnel-1  | 2024-01-26T16:11:03.197927771Z 2024-01-26T16:11:03.197188Z  INFO rss_funnel::server: listening on 0.0.0.0
rss-funnel-1  | 2024-01-26T16:11:03.199455604Z Error: Io(Error { kind: InvalidInput, message: "invalid socket address" })
```

**Comment by shouya** [comment]
@uGeek 

Oh sorry, I missed the port in the command line. Please try this:

```yaml
    command: /rss-funnel -c /funnel.yaml server -b 0.0.0.0:4080
```

**Comment by uGeek** [comment]
Excellent! Now it works correctly!

I am running docker on a Raspberry Pi 4 with arm64

Thank you so much

**Comment by shouya** [comment]
Glad to help!
