### ISSUE TITLE
Feature: Filter articles by title

### ISSUE THREAD

**Issue by jhotmann** [shouya/rss-funnel#5]
First of all, this is a great project and I'm excited to use it more. I use Miniflux and it has some similar features but I like the ability to apply the same rules to multiple sites and store config in source control.

A filter that would be nice to have is one that can filter out posts that match a regex string (or list of regexes).

**Comment by shouya** [comment]
That's easy to do, I'll get it implemented for the next version. For the time being, you can use JS to do the filtering if you want. Here's an example:

```yaml
  - path: /show-or-ask-hn.xml
    source: https://news.ycombinator.com/rss
    filters:
      - js: |
          function modify_post(feed, post) {
            if (/Show HN/.test(post.title)) {
              return post;
            } else if (/Ask HN/.test(post.title)) {
              return post;
            } else {
              return null;
            }
          }
```
