### ISSUE TITLE
Authentication for UI

### ISSUE THREAD

**Issue by uGeek** [shouya/rss-funnel#56]
I have currently set up the service with a reverse proxy and I have exposed both the feeds and the administration UI, which is fantastic (It was a great idea). I think that the UI should have the possibility to set a username and password, leaving the feeds open to the network on the same server and being able to access them.

Could you implement this feature?

**Comment by shouya** [comment]
My reason against having a login was that the feed endpoints are all public and the inspector ui is only readonly. And if the user is really concerned about privacy, they could just disable the inspector ui. So then I was hesitate about adding this feature.

Indeed, I do admit inspector UI exposed the enumeration of the endpoints, which could be a security/privacy loophole.

I intend to make the UI a tool to inspect, debug, and help writing the config. And that could include an editor support in the future. In that case, a login is definitely needed.

Either way, I now agree with you on the necessity of adding support for authentication. But currently I'm not fully sure about on how it should be done. Probably via config? Or command line options? Also, storing session info would make inspector ui backend stateful, which is something I was avoiding from the start. Then perhaps we should use JWT? -- Just to name a few questions to consider.

Let me sort things out then I'll implement it. Meanwhile I welcome any suggestions.

**Comment by shouya** [comment]
@uGeek: the feature is implemented in #70. It will be included in next release.

**Comment by uGeek** [comment]
Thanks
