### ISSUE TITLE
Sort by date of publication

### ISSUE THREAD

**Issue by uGeek** [shouya/rss-funnel#65]
Mixing sources works perfectly, but it would be possible to sort the mixed feed by publication date after it has been created?. 

Currently, what I have observed is that it downloads the first feed, then the second, and so on. It adds them together and the client sorts them by publication order. This can become a problem when you trim the feed distance. I have currently created a feed of six podcasts. Since there are many entries, the size of the feed goes to 16 Mb. If I leave the last ten publications, only the first ten publications are shown, so if the first feed has more than ten, only publications from the first feed would be seen. I think it would be best to first create the feed as it is now and then sort it by publication date.

**Comment by shouya** [comment]
It's already been implemented in https://github.com/shouya/rss-funnel/pull/58. It'll be included in next release :)
