### ISSUE TITLE
Issue with Discard/Keep_Only Filter Not Matching Inside Non-Standard Fields

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#92]
Currently, there is an issue with the discard/keep_only filter not matching inside non-standard fields, specifically the media:description tag within the media namespace.

**Comment by shouya** [comment]
Fixed in https://github.com/shouya/rss-funnel/pull/100. Now your original filter should work without having to assign the `description` to the `content` field.

You can try out the nightly image (https://github.com/shouya/rss-funnel/pkgs/container/rss-funnel).
