### ISSUE TITLE
Google News, Meneame,...Original sources

### ISSUE THREAD

**Issue by uGeek** [shouya/rss-funnel#94]
It would be possible with js to extract the original source url of articles from the feeds of Google News, Meneame, ..... Normally the url provided by the feed is to access their servers and they are the ones that provide you with the original url. But would it be possible for rss-funnel to extract the original url and return the rss feed with the original title and source?

Here are some examples of feeds
Google News:  https://news.google.com/rss/search?q=openai&hl=es&gl=ES&ceid=ES:es

Meneame is a well-known social network in Spain and acts in a similar way: https://www.meneame.net/rss2.php

**Comment by shouya** [comment]
Finding the original source requires different techniques for difference news aggregation websites. In generally it should be possible as long as a human is able to find it.

For example, in Meneame's [article page](https://www.meneame.net/m/actualidad/coi-arremete-contra-juegos-amistad-promovidos-rusia), there is a link "[es-us.noticias.yahoo.com](https://www.meneame.net/go/link/3920286)" which points to the source. The link itself is not the original source, but requesting it responds with a 301 redirection to the original source. That means you should be able to make a request using the [fetch API](https://github.com/shouya/rss-funnel/wiki/JavaScript-API#fetch-unreleased) to retrieve the redirected `location` from the header. (Try `curl -I https://www.meneame.net/go/link/3920286`)

For google news, the article's urls look like `https://news.google.com/rss/articles/CBMijAFodHRwczovL3d3dy5sYXZvemRlZ2FsaWNpYS5lcy9ub3RpY2lhL3NvY2llZGFkLzIwMjQvMDMvMTgvb3BlbmFpLWFkZWxhbnRhLWdlbmVyYWRvci12aWRlb3Mtc29yYS1sYW56YXJhLWZpbmFsZXMtYW5vLzAwMDNfMjAyNDAzRzE4UDMzOTkxLmh0bdIBoQFodHRwczovL3d3dy5sYXZvemRlZ2FsaWNpYS5lcy9hbXAvbm90aWNpYS9zb2NpZWRhZC8yMDI0LzAzLzE4L29wZW5haS1hZGVsYW50YS1nZW5lcmFkb3ItdmlkZW9zLXNvcmEtbGFuemFyYS1maW5hbGVzLWFuby8wMDAzXzIwMjQwM0cxOFAzMzk5MS5odG0_dXRtX2NhbXBhaWduPWFtcA?oc=5`. The middle part, the `CBMijAFodH...aWduPWFtcA` is the base64 encoded string of `https://www.lavozdegalicia.es/noticia/sociedad/2024/03/18/openai-adelanta-generador-videos-sora-lanzara-finales-ano/0003_202403G18P33991.htm�https://www.lavozdegalicia.es/amp/noticia/sociedad/2024/03/18/openai-adelanta-generador-videos-sora-lanzara-finales-ano/0003_202403G18P33991.htm`. This means if you can decode base64 in it you should be able to get the original source this way. Unfortunately there is no built-in  javascript API that does base64 encoding or decoding in rss-funnel yet. However, base64 API is a feature I can add in the future.

**Comment by shouya** [comment]
FYI the base64 decoding API was implemented in #108.
